### ISSUE TITLE
Using HTML text in handlebars fields doesn't compile properly

### ISSUE THREAD

**Issue by robertmausser** [adaptlearning/adapt-contrib-instructionError#9]
### Subject of the issue/enhancement/features
When using html (< b >, < q > etc) in instruction text, it doesn't compile properly in the notify popup. It shows the <q> instead of an actual quotation. 

### Your environment
* Adapt 5
* All browers
* All OSes

### Steps to reproduce
Use any html scripting in the instruciton text area.

### Expected behaviour
HTML should render properly

### Actual behaviour
HTML scripting shows up in notify body text. 

### Screenshots (if you can)

https://snipboard.io/aZFSk4.jpg

**Comment by oliverfoster** [comment]
Curious.

https://github.com/adaptlearning/adapt-contrib-instructionError/blob/a486c90d1c24a2c7e8f008973c301240f5a13b04/js/adapt-contrib-instructionError.js#L26-L27

You can see here that it does convert handlebars to html.

The example.json however is not formatted correctly at line: 
https://github.com/adaptlearning/adapt-contrib-instructionError/blob/a486c90d1c24a2c7e8f008973c301240f5a13b04/example.json#L5
Which should be triple curly braced:
```js
"body": "{{#if instruction}}{{{instruction}}}{{else}}Please complete the question and then select Submit.{{/if}}"
```

**Comment by oliverfoster** [comment]
did that fix it? @robertmausser
